terms = {
"Anguilla":"",
"Afghanistan":"",
"Albania":"",
"Algeria":"",
"Andorra":"",
"Angola":"",
"Antigua":"",
"Barbuda":"",
"Argentina":"",
"Armenia":"",
"Aruba":"",
"Australia":"",
"Austria":"",
"Azerbaijan":"",
"Bahamas":"",
"Bahrain":"",
"Bangladesh":"",
"Barbados":"",
"Belarus":"",
"Belgium":"",
"Belize":"",
"Benin":"",
"Bermuda":"",
"Bhutan":"",
"Bolivia":"",
"Bosnia":"",
"Botswana":"",
"Brazil":"",
"Brunei":"",
"Bulgaria":"",
"Burkina Faso":"",
"Burundi":"",
"Cambodia":"",
"Cameroon":"",
"Canada":"",
"Cape Verde":"",
"Cayman Islands":"",
"Central African Republic":"",
"Chad":"",
"Chile":"",
"China":"",
"Colombia":"",
"Comoros":"",
"Congo":"",
"Cook Islands":"",
"Costa Rica":"",
"Croatia":"",
"Cuba":"",
"Curacao":"",
"Cyprus":"",
"Czech Republic":"",
"Denmark":"",
"Djibouti":"",
"Dominica":"",
"Dominican Republic":"",
"DR Congo":"",
"East Timor":"",
"Ecuador":"",
"Egypt":"",
"El Salvador":"",
"Equatorial Guinea":"",
"Eritrea":"",
"Estonia":"",
"Ethiopia":"",
"Falkland Islands":"",
"Faroe Islands":"",
"Fiji":"",
"Finland":"",
"France":"",
"French Guiana":"",
"French Polynesia":"",
"Gabon":"",
"Gambia":"",
"Georgia":"",
"Germany":"",
"Ghana":"",
"Gibraltar":"",
"Greece":"",
"Greenland":"",
"Grenada":"",
"Guadeloupe":"",
"Guam":"",
"Guatemala":"",
"Guinea":"",
"Guinea-Bissau":"",
"Guyana":"",
"Haiti":"",
"Honduras":"",
"Hong Kong":"",
"Hungary":"",
"Iceland":"",
"India":"",
"Indonesia":"",
"Iran":"",
"Iraq":"",
"Ireland":"",
"Israel":"",
"Italy":"",
"Ivory Coast":"",
"Jamaica":"",
"Japan":"",
"Jordan":"",
"Kazakhstan":"",
"Kenya":"",
"Kiribati":"",
"Kuwait":"",
"Kyrgyzstan":"",
"Laos":"",
"Latvia":"",
"Lebanon":"",
"Lesotho":"",
"Liberia":"",
"Libya":"",
"Liechtenstein":"",
"Lithuania":"",
"Luxembourg":"",
"Macau":"",
"Madagascar":"",
"Malawi":"",
"Malaysia":"",
"Maldives":"",
"Mali":"",
"Malta":"",
"Marshall Islands":"",
"Martinique":"",
"Mauritania":"",
"Mauritius":"",
"Mayotte":"",
"Mexico":"",
"Micronesia":"",
"Moldova":"",
"Monaco":"",
"Mongolia":"",
"Montenegro":"",
"Montserrat":"",
"Morocco":"",
"Mozambique":"",
"Myanmar":"",
"Namibia":"",
"Nauru":"",
"Nepal":"",
"Netherlands":"",
"New Caledonia":"",
"New Zealand":"",
"Nicaragua":"",
"Niger":"",
"Nigeria":"",
"Niue":"",
"North Korea":"",
"Northern Mariana Islands":"",
"Norway":"",
"Not Applicable":"",
"Oman":"",
"Pakistan":"",
"Palau":"",
"Palestinian Territory":"",
"Panama":"",
"Papua New Guinea":"",
"Paraguay":"",
"Peru":"",
"Philippines":"",
"Poland":"",
"Portugal":"",
"Puerto Rico":"",
"Qatar":"",
"Republic of Macedonia":"",
"Reunion":"",
"Romania":"",
"Russia":"",
"Rwanda":"",
"Saint Kitts and Nevis":"",
"Saint Lucia":"",
"Saint Vincent and the Grenadines":"",
"Samoa":"",
"San Marino":"",
"Sao Tome and Principe":"",
"Saudi Arabia":"",
"Senegal":"",
"Serbia":"",
"Seychelles":"",
"Sierra Leone":"",
"Singapore":"",
"Slovakia":"",
"Slovenia":"",
"Solomon Islands":"",
"Somalia":"",
"South Africa":"",
"South Korea":"",
"Spain":"",
"Sri Lanka":"",
"St. Helena":"",
"St. Pierre and Miquelon":"",
"Sudan":"",
"Suriname":"",
"Swaziland":"",
"Sweden":"",
"Switzerland":"",
"Syria":"",
"Taiwan":"",
"Tajikistan":"",
"Tanzania":"",
"Thailand":"",
"Togo":"",
"Tokelau":"",
"Tonga":"",
"Trinidad and Tobago":"",
"Tunisia":"",
"Turkey":"",
"Turkmenistan":"",
"Turks and Caicos Islands":"",
"Tuvalu":"",
"Uganda":"",
"Ukraine":"",
"United Arab Emirates":"",
"United Kingdom":"",
"United States":"",
"Unknown":"",
"Uruguay":"",
"Uzbekistan":"",
"Vanuatu":"",
"Vatican City State (Holy See)":"",
"Venezuela":"",
"Vietnam":"",
"Virgin Islands":"",
"Wallis and Futuna Islands":"",
"Yemen":"",
"Zambia":"",
"Zimbabwe":"",       
"airport": "",
"check-in": "",
"fly": "",
"land": "",
"landing": "",
"plane": "",
"take off": "",
"destination": "",
"journey": "",
"passenger": "",
"route": "",
"travel": "",
"travel agent": "",
"trip": "",
"camp": "",
"go camping": "",
"charger flight": "",
"cruise": "",
"excursion": "",
"hostel": "",
"hotel": "",
"luggage": "",
"motel": "",
"package holiday": "",
"self-catering holiday": "",
"sightseeing": "",
"go sightseeing": "",
"suitcase": "",
"tour": "",
"tourism": "",
"tourist": "",
"vacation": "",
"bicycle": "",
"bike": "",
"bus": "",
"bus station": "",
"car": "",
"coach": "",
"coach station": "",
"lane": "",
"motorbike": "",
"motorway": "",
"rail": "",
"go by rail": "",
"railway": "",
"railway station": "",
"road": "",
"main road": "",
"minor road": "",
"taxi": "",
"traffic": "",
"train": "",
"tube": "",
"underground": "",
"subway": "",
"boat": "",
"crossing": "",
"ferry": "",
"port": "",
"sail": "",
"sea": "",
"set sail": "",
"ship": "",
"voyage": "",
"board": "",
"go by": "",
"go on board": "",
"get on board": "",
"hitch-hike": "",
"set off": ""
}
