terms = {
"airport": "",
"check-in": "",
"fly": "",
"land": "",
"landing": "",
"plane": "",
"take off": "",
"destination": "",
"journey": "",
"passenger": "",
"route": "",
"travel": "",
"travel agent": "",
"trip": "",
"camp": "",
"go camping": "",
"charger flight": "",
"cruise": "",
"excursion": "",
"hostel": "",
"hotel": "",
"luggage": "",
"motel": "",
"package holiday": "",
"self-catering holiday": "",
"sightseeing": "",
"go sightseeing": "",
"suitcase": "",
"tour": "",
"tourism": "",
"tourist": "",
"vacation": "",
"bicycle": "",
"bike": "",
"bus": "",
"bus station": "",
"car": "",
"coach": "",
"coach station": "",
"lane": "",
"motorbike": "",
"motorway": "",
"rail": "",
"go by rail": "",
"railway": "",
"railway station": "",
"road": "",
"main road": "",
"minor road": "",
"taxi": "",
"traffic": "",
"train": "",
"tube": "",
"underground": "",
"subway": "",
"boat": "",
"crossing": "",
"ferry": "",
"port": "",
"sail": "",
"sea": "",
"set sail": "",
"ship": "",
"voyage": "",
"board": "",
"go by": "",
"go on board": "",
"get on board": "",
"hitch-hike": "",
"set off": ""
}
